# Generated by Django 5.1.6 on 2026-09-15 20:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120, unique=True)),
                ("slug", models.SlugField(max_length=120, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="ES, MX, IT, ON (Ontario)", max_length=8, unique=True
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                (
                    "regulator",
                    models.CharField(
                        help_text="DGOJ, SEGOB, ADM, AGCO", max_length=120
                    ),
                ),
                ("tld", models.CharField(default=".es", max_length=12)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                ("legal_notice_en", models.TextField(blank=True)),
                ("legal_notice_es", models.TextField(blank=True)),
                ("help_line", models.CharField(blank=True, max_length=160)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("running", "Running"),
                            ("success", "Success"),
                            ("partial", "Partial"),
                            ("failed", "Failed"),
                        ],
                        default="running",
                        max_length=16,
                    ),
                ),
                ("trigger", models.CharField(default="beat", max_length=32)),
                ("brands_total", models.PositiveIntegerField(default=0)),
                ("brands_ok", models.PositiveIntegerField(default=0)),
                ("brands_failed", models.PositiveIntegerField(default=0)),
                ("placements_captured", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-started_at"],
            },
        ),
        migrations.CreateModel(
            name="Game",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("slug", models.SlugField(max_length=180, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("live_roulette", "Live Roulette"),
                            ("live_blackjack", "Live Blackjack"),
                            ("game_show", "Game Show"),
                            ("megaways", "Megaways"),
                            ("classic_slot", "Classic Slot"),
                            ("crash", "Crash Game"),
                            ("table", "Blackjack / Table"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "is_local_favourite",
                    models.BooleanField(
                        default=False,
                        help_text="Market-specific title, e.g. MGA Games licensed IP in Spain",
                    ),
                ),
                ("note_en", models.TextField(blank=True)),
                ("note_es", models.TextField(blank=True)),
                (
                    "provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="games",
                        to="index.provider",
                    ),
                ),
            ],
            options={
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=120, unique=True)),
                (
                    "short_code",
                    models.CharField(help_text="Badge label, e.g. CODE", max_length=6),
                ),
                ("domain", models.CharField(max_length=180, unique=True)),
                ("homepage_url", models.URLField()),
                ("operator_group", models.CharField(blank=True, max_length=160)),
                ("licence_number", models.CharField(blank=True, max_length=80)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("delisted", "Delisted"),
                        ],
                        default="active",
                        max_length=12,
                    ),
                ),
                ("selectors", models.JSONField(blank=True, default=dict)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("consecutive_failures", models.PositiveIntegerField(default=0)),
                (
                    "region",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="brands",
                        to="index.region",
                    ),
                ),
            ],
            options={
                "ordering": ["region__code", "name"],
            },
        ),
        migrations.CreateModel(
            name="ScrapeLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("success", "Success"), ("failed", "Failed")],
                        max_length=12,
                    ),
                ),
                ("games_found", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("duration_ms", models.PositiveIntegerField(default=0)),
                ("executed_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scrape_logs",
                        to="index.brand",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="index.scraperun",
                    ),
                ),
            ],
            options={
                "ordering": ["-executed_at"],
            },
        ),
        migrations.CreateModel(
            name="HomepagePlacement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Carousel"),
                            ("grid", "Top Pick Grid"),
                            ("live_section", "Live Section"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "position",
                    models.PositiveIntegerField(
                        default=0, help_text="Index within its section"
                    ),
                ),
                ("raw_label", models.CharField(blank=True, max_length=220)),
                (
                    "detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="index.brand",
                    ),
                ),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="index.game",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="placements",
                        to="index.scraperun",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnmatchedTile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("raw_label", models.CharField(max_length=220)),
                ("normalized", models.CharField(db_index=True, max_length=220)),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Carousel"),
                            ("grid", "Top Pick Grid"),
                            ("live_section", "Live Section"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("best_score", models.FloatField(default=0)),
                ("resolved", models.BooleanField(default=False)),
                ("seen_at", models.DateTimeField(auto_now_add=True)),
                (
                    "best_guess",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="index.game",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unmatched",
                        to="index.brand",
                    ),
                ),
            ],
            options={
                "ordering": ["-best_score"],
            },
        ),
        migrations.CreateModel(
            name="GameAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
                ("normalized", models.CharField(db_index=True, max_length=200)),
                (
                    "game",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="index.game",
                    ),
                ),
            ],
            options={
                "unique_together": {("game", "normalized")},
            },
        ),
        migrations.AddIndex(
            model_name="game",
            index=models.Index(
                fields=["category"], name="index_game_categor_6c75e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="brand",
            index=models.Index(
                fields=["status", "region"], name="index_brand_status_239d70_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapelog",
            index=models.Index(
                fields=["brand", "-executed_at"], name="index_scrap_brand_i_384892_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageplacement",
            index=models.Index(
                fields=["detected_at", "brand"], name="hp_detected_brand_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageplacement",
            index=models.Index(
                fields=["created_at", "brand"], name="hp_created_brand_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageplacement",
            index=models.Index(
                fields=["created_at", "game"], name="hp_created_game_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="homepageplacement",
            index=models.Index(
                fields=["game", "brand", "created_at"], name="hp_game_brand_created_idx"
            ),
        ),
    ]
